name: klausurscreen
description: Projektion zur Verwendung während Klausuren
version: 1.0.1
author: Hendrik Fichtenberger <oss@hendrik-fichtenberger.de>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
